pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws_access_key_id_nonprod')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key_nonprod')
        AWS_DEFAULT_REGION    = 'ap-south-1'
        github_creds          = credentials('jenkins-github-sre')
        AWS_REGION            = 'ap-south-1'
        AWS_ACCOUNT_ID        = '145023133364'
        ECS_CLUSTER_NAME      = 'central-platforms-nonprod'
        ECR_REPO_NAME         = 'retailtech-url-shortner-np'
        ECS_SERVICE_NAME      = 'arzooo-url-shortner-np'
    }

    stages {

        stage("Clone Git Repo") {
            steps {
                script {
                    git branch: "development_v2", credentialsId: 'jenkins-github-sre', url: 'https://github.com/arzooo-tech/arzooo-url-shortner.git'
                }
            }
        }
      
        stage("Build and Push Docker Image") {
            steps {
                script {
                    // Generate tags
                    def commitHash = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    def imageTagLatest = "latest"
                    def imageTagSHA = commitHash

                    // Log in to ECR
                    sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

                    // Build, tag, and push Docker images
                    sh "docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${imageTagLatest} -t ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${imageTagSHA} ."
                    sh "docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${imageTagLatest}"
                    sh "docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO_NAME}:${imageTagSHA}"

                    // Update ECS service
                    sh "aws ecs update-service --force-new-deployment --service ${ECS_SERVICE_NAME} --cluster ${ECS_CLUSTER_NAME} --region ${AWS_REGION}"
                }
            }
        }
    }
}
